// Regenerates extension/lib/psl-data.js from the Public Suffix List.
// Usage: npm run update-psl
import fs from 'node:fs';
import path from 'node:path';
import { domainToASCII } from 'node:url';

const SOURCE = 'https://publicsuffix.org/list/public_suffix_list.dat';
const OUT = path.resolve(import.meta.dirname, '../extension/lib/psl-data.js');

const res = await fetch(SOURCE);
if (!res.ok) throw new Error(`download failed: HTTP ${res.status}`);
const text = await res.text();
if (!text.includes('===BEGIN ICANN DOMAINS===') || !text.includes('===END PRIVATE DOMAINS===')) {
  throw new Error('unexpected list format');
}

// Rules are punycoded label by label so they match Chrome's ASCII hostnames; "*" and "!" are kept.
function toAscii(rule) {
  const prefix = rule.startsWith('!') ? '!' : '';
  const labels = rule.slice(prefix.length).split('.');
  const ascii = labels.map((label) => (label === '*' ? '*' : domainToASCII(label)));
  if (ascii.some((label) => label === '')) throw new Error(`cannot convert rule: ${rule}`);
  return prefix + ascii.join('.').toLowerCase();
}

const rules = [
  ...new Set(
    text
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line !== '' && !line.startsWith('//'))
      .map(toAscii),
  ),
];
if (rules.length < 5000) throw new Error(`too few rules: ${rules.length}`);

fs.writeFileSync(
  OUT,
  `// Generated by scripts/update-psl.js from ${SOURCE}. Do not edit.\n` +
    '// Public Suffix List data, licensed under the Mozilla Public License 2.0 (https://mozilla.org/MPL/2.0/).\n' +
    `export const PSL_RULES = ${JSON.stringify(rules.join('\n'))};\n`,
);
console.log(`${rules.length} rules -> ${path.relative(process.cwd(), OUT)} (${fs.statSync(OUT).size} bytes)`);
